version: "3.9"

services:
  notifier_redirecter:
    build: .
    #image: ghcr.io/dsharpplus/notifierredirecter:latest
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./database.db:/src/database.db
      - ./logs:/src/logs