name: Publish Docker Image
on:
  push:
    branches:
      - master

jobs:
  push-to-registery:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner  }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: VERSION=${{ steps.previoustag.outputs.tag }}
          tags: |
            ghcr.io/dsharpplus/notifierredirecter:latest
            ghcr.io/dsharpplus/notifierredirecter:${{ steps.previoustag.outputs.tag }}
