on:
  push:
    branches:
      - main
    paths:
      - "res/icon.svg"
      - "tools/generate-assets.sh"
      - ".github/workflows/resources.yml"

jobs:
  build-pr:
    name: "Regenerate Resource Files"
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate Assets
        run: tools/generate-assets.sh